### PR TITLE
feat(all): Merging L2/L3 node client and proposer/prover

### PR DESCRIPTION
**Pull request by liray-unendlich**
I just updated my repository docker-compose.yml to normalize L2/L3 nodes and proposer/prover running.

How to use:
1. Clone this repository
2. change the branch to l2-l3-merge
3. edit .env
In this environmental file, we added all variables in L2/L3 nodes/proposer/prover settings. you can choose to host L2 or L3 nodes within the same server or other servers.
5. run docker-compose.yml

I hope this will make it easier to host or set up L2/L3 nodes.
An easier way contributes to decentralization.

To merge this PR, firstly we need to rewrite or update our set up documents.

### CODE REVIEW

**Comment by 2manslkh** [comment]
Definitely convenient when trying to spin up an L3 as an L2 is a prerequisite.

However, users are not meant to spin up 2 Taikos at the same time by default.

**Comment by liray-unendlich** [comment]
I understand your concerns and appreciate your feedback. Nonetheless, I firmly believe that even in scenarios where L2/L3 are hosted on separate servers, this script offers superior convenience compared to the existing one.

**Comment by Nakochi-crypto** [comment]
Using profiles might be better. 

```
# L2
docker compose up -d
docker compose logs -f
docker compose down

# L3
docker compose -f docker-compose.l3.yml --env-file .env.l3 up -d
docker compose -f docker-compose.l3.yml --env-file .env.l3 logs -f
docker compose -f docker-compose.l3.yml --env-file .env.l3 down
```

will be

```
# L2
docker compose --profile l2 up -d
docker compose --profile l2 logs -f
docker compose --profile l2 down

# L3
docker compose --profile l3 up -d
docker compose --profile l3 logs -f
docker compose --profile l3 down
```

To run both L2 and L3, simply add `---profile l2 --profile l3`.

cf. https://docs.docker.com/compose/profiles/

Can I create a pull request based on this one?

**Comment by d1onys1us** [comment]
> Using profiles might be better.
> 
> ```
> # L2
> docker compose up -d
> docker compose logs -f
> docker compose down
> 
> # L3
> docker compose -f docker-compose.l3.yml --env-file .env.l3 up -d
> docker compose -f docker-compose.l3.yml --env-file .env.l3 logs -f
> docker compose -f docker-compose.l3.yml --env-file .env.l3 down
> ```
> 
> will be
> 
> ```
> # L2
> docker compose --profile l2 up -d
> docker compose --profile l2 logs -f
> docker compose --profile l2 down
> 
> # L3
> docker compose --profile l3 up -d
> docker compose --profile l3 logs -f
> docker compose --profile l3 down
> ```
> 
> To run both L2 and L3, simply add `---profile l2 --profile l3`.
> 
> cf. https://docs.docker.com/compose/profiles/
> 
> Can I create a pull request based on this one?

i think that sounds like a good idea! please feel free. thank you :) keep in mind we are thinking about creating a rust CLI tool which can alias these commands. you can see more in my comment here: https://github.com/taikoxyz/simple-taiko-node/pull/106 . open to any of your ideas/feedback.

**Comment by Nakochi-crypto** [comment]
I tried merging docker-compose.yml and found that it is hard to maintain backward compatibility for existing nodes. A launcher script will be much better.

**Comment by d1onys1us** [comment]
thanks for the PR @liray-unendlich we will close this for now, as we are re-working the simple-taiko-node design.

**Pull request closed without merging**
