### PR TITLE
feat(node): allow uprotected txs flag for proxy deploy for devrel team

### PR DESCRIPTION
**Pull request by cyberhorsey**
defaults to false if variable is not set

### CODE REVIEW

**Comment by davidtaikocha** [comment]
Since our node has enabled EIP-155, emm not sure will this work?

**Comment by davidtaikocha** [comment]
> @davidtaikocha
> 
> We are trying to deploy a deterministic proxy contract.
> 
> This method: https://github.com/Arachnid/deterministic-deployment-proxy requires us to send a signed transaction with RLP only valid before EIP-155.
> 
> Therefore, we need to set the following flag
> 
> ```
> rpc.allow-unprotected-txs=true
> ```
> 
> to allow the unprotected transaction to go through.

emmm actually i don't think this requires a PR to merge that flag into our public codebase. Looks like the reason why that script requires to send a signed transaction with RLP only valid before EIP-155 is because this script is too old (4 years ago) (correct me if i'm wrong)?  Sending pre-EIP-155 txs with any private key has some potential security issues right? Like those transactions in our testnet can be re-played in mainnet.  So updating the script to make it sending post-EIP-155 txs sounds like a more reasonable approach?

**Comment by MarcusWentz** [comment]
The RLP does not include EIP-155 intentionally here
https://github.com/Arachnid/deterministic-deployment-proxy
for it to be reused cross chain.

Can I use this branch as a reference to add this flag if we choose not to merge?

**Comment by davidtaikocha** [comment]
> Updating the script to make it sending post-EIP-155 txs sounds like a more reasonable approach?

image

I still thinking this is the right way to do that? Sending a unprotected transaction in a EIP-155 enabled chain should be a very very unrecommended behavior and nobody should do that nowadays?

**Comment by davidtaikocha** [comment]
> The RLP does not include EIP-155 intentionally here https://github.com/Arachnid/deterministic-deployment-proxy for it to be reused cross chain.
> 
> Can I use this branch as a reference to add this flag if we choose not to merge?

But if u think this `deterministic-deployment-proxy` is a necessary for u at current stage... u can add that flag in a branch but not merge it into main.

**Comment by cyberhorsey** [comment]
> Close this one since we won't merge that flag config into `main` branch.

Yes this is just for devrel to use, apparently they need to not use EIP-155, they talked to the creators of the script and for some reason it can't function the same way without pre-EIP 155. So it's not intended for community use, or anyone besides Marcus really.

**Pull request closed without merging**
